#!/bin/sh
# This script resets the USB hub after boot.
echo 0 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio0/direction
echo 0 > /sys/class/gpio/gpio0/value
sleep 1s
echo 1 > /sys/class/gpio/gpio0/value

